### ISSUE TITLE
Guru Meditation Error

### ISSUE THREAD

**Issue by freetoair** [Risto97/ESP32-2432S022_lvgl_example#1]
`Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4016951f  PS      : 0x00060c30  A0      : 0x80165da4  A1      : 0x3ffd0d20  
--- 0x4016951f: ap_get_sta at /home/nb/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/components/wpa_supplicant/src/ap/sta_info.c:46

A2      : 0x00000000  A3      : 0x00000012  A4      : 0x3ffd0d37  A5      : 0x3ffd0d30  
A6      : 0x00000003  A7      : 0x00000002  A8      : 0x00000000  A9      : 0x3ffd0ce0  
A10     : 0x00000000  A11     : 0x00000001  A12     : 0x3ffd13f0  A13     : 0x3ffd0d37  
A14     : 0x00000001  A15     : 0xb33fffff  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000017  LBEG    : 0x4000c28c  LEND    : 0x4000c296  LCOUNT  : 0x00000000  
--- 0x4000c28c: __memcpy_aux in ROM
0x4000c296: __memcpy_aux in ROM

Backtrace: 0x4016951c:0x3ffd0d20 0x40165da1:0x3ffd0d40 0x4014aac8:0x3ffd0d60 0x40148332:0x3ffd0de0 0x40092999:0x3ffd0e00
--- 0x4016951c: ap_get_sta at /home/nb/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/components/wpa_supplicant/src/ap/sta_info.c:43
0x40165da1: wpa3_hostap_handle_auth at /home/nb/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/components/wpa_supplicant/esp_supplicant/src/esp_wpa3.c:581
0x4014aac8: wifi_set_config_process at ??:?
0x40148332: ieee80211_ioctl_process at ??:?
0x40092999: ppTask at ??:?

Hi,

In sdkconfig you have to select Optimization level: small, but after that the above occurs.
Can you post your sdkconfig ?

`

**Comment by Risto97** [comment]
It seems like I forgot to change the git remote on my local repo, and pushed some commits from a later project.

If you are interested in a working LVGL demo, you can try an earlier commit 17e3b50d1f7bfe7e65b9d9cc187c01e4bc547f79

I don't know if it will help, but it will simplify the project quite a bit and you can debug from there.

sdkconfig should be up to date on the remote.

**Comment by freetoair** [comment]
OK, this commit work. Thanks 
Pozdrav !
